import Card from './components/card/card';
import Card2 from './components/card2/card2';
import Card3 from './components/card3/card3';
import Card4 from './components/card4/card4';
import Card5 from './components/card5/card5';
import Card6 from './components/card6/card6';
import Card7 from './components/card7/card7';
import Card8 from './components/card8/card8';
import Card9 from './components/card9/card9';
import Card10 from './components/card10/card10';
import Card11 from './components/card11/card11';
import Card12 from './components/card12/card12';
import Card13 from './components/card13/card13';
import Card14 from './components/card14/card14';
import Palette from './components/palette/palette';

window.customElements.define('comp-1', Card);
window.customElements.define('comp-2', Card2);
window.customElements.define('comp-3', Card3);
window.customElements.define('comp-4', Card4);
window.customElements.define('comp-5', Card5);
window.customElements.define('comp-6', Card6);
window.customElements.define('comp-7', Card7);
window.customElements.define('comp-8', Card8);
window.customElements.define('comp-9', Card9);
window.customElements.define('comp-10', Card10);
window.customElements.define('comp-11', Card11);
window.customElements.define('comp-12', Card12);
window.customElements.define('comp-13', Card13);
window.customElements.define('comp-14', Card14);
window.customElements.define('my-palette', Palette);
